# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tenseal_data_pb2 as tenseal__data__pb2


class SafeTransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MaxValue = channel.unary_unary(
                '/SafeTransmission/MaxValue',
                request_serializer=tenseal__data__pb2.encrypted.SerializeToString,
                response_deserializer=tenseal__data__pb2.encrypted.FromString,
                )
        self.MinValue = channel.unary_unary(
                '/SafeTransmission/MinValue',
                request_serializer=tenseal__data__pb2.encrypted.SerializeToString,
                response_deserializer=tenseal__data__pb2.encrypted.FromString,
                )


class SafeTransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MaxValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MinValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SafeTransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MaxValue': grpc.unary_unary_rpc_method_handler(
                    servicer.MaxValue,
                    request_deserializer=tenseal__data__pb2.encrypted.FromString,
                    response_serializer=tenseal__data__pb2.encrypted.SerializeToString,
            ),
            'MinValue': grpc.unary_unary_rpc_method_handler(
                    servicer.MinValue,
                    request_deserializer=tenseal__data__pb2.encrypted.FromString,
                    response_serializer=tenseal__data__pb2.encrypted.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SafeTransmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SafeTransmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MaxValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeTransmission/MaxValue',
            tenseal__data__pb2.encrypted.SerializeToString,
            tenseal__data__pb2.encrypted.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MinValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SafeTransmission/MinValue',
            tenseal__data__pb2.encrypted.SerializeToString,
            tenseal__data__pb2.encrypted.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
