# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tenseal_data.proto\"$\n\tencrypted\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x32Z\n\x10SafeTransmission\x12\"\n\x08MaxValue\x12\n.encrypted\x1a\n.encrypted\x12\"\n\x08MinValue\x12\n.encrypted\x1a\n.encryptedb\x06proto3')



_ENCRYPTED = DESCRIPTOR.message_types_by_name['encrypted']
encrypted = _reflection.GeneratedProtocolMessageType('encrypted', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTED,
  '__module__' : 'tenseal_data_pb2'
  # @@protoc_insertion_point(class_scope:encrypted)
  })
_sym_db.RegisterMessage(encrypted)

_SAFETRANSMISSION = DESCRIPTOR.services_by_name['SafeTransmission']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENCRYPTED._serialized_start=22
  _ENCRYPTED._serialized_end=58
  _SAFETRANSMISSION._serialized_start=60
  _SAFETRANSMISSION._serialized_end=150
# @@protoc_insertion_point(module_scope)
