# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tenseal_data.proto\"@\n\trequestOP\x12\n\n\x02op\x18\x01 \x01(\t\x12\x12\n\ntable_name\x18\x02 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x03 \x01(\t\"&\n\x11responseEncResult\x12\x11\n\tencResult\x18\x01 \x01(\x0c\x32I\n\x15\x44\x61tabaseServerService\x12\x30\n\x0eQueryOperation\x12\n.requestOP\x1a\x12.responseEncResultb\x06proto3')



_REQUESTOP = DESCRIPTOR.message_types_by_name['requestOP']
_RESPONSEENCRESULT = DESCRIPTOR.message_types_by_name['responseEncResult']
requestOP = _reflection.GeneratedProtocolMessageType('requestOP', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTOP,
  '__module__' : 'tenseal_data_pb2'
  # @@protoc_insertion_point(class_scope:requestOP)
  })
_sym_db.RegisterMessage(requestOP)

responseEncResult = _reflection.GeneratedProtocolMessageType('responseEncResult', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEENCRESULT,
  '__module__' : 'tenseal_data_pb2'
  # @@protoc_insertion_point(class_scope:responseEncResult)
  })
_sym_db.RegisterMessage(responseEncResult)

_DATABASESERVERSERVICE = DESCRIPTOR.services_by_name['DatabaseServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTOP._serialized_start=22
  _REQUESTOP._serialized_end=86
  _RESPONSEENCRESULT._serialized_start=88
  _RESPONSEENCRESULT._serialized_end=126
  _DATABASESERVERSERVICE._serialized_start=128
  _DATABASESERVERSERVICE._serialized_end=201
# @@protoc_insertion_point(module_scope)
