# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_aggregate_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etenseal_aggregate_server.proto\"6\n\x0b\x61ggr_params\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x12\n\nparams_msg\x18\x02 \x01(\x0c\x32G\n\x18\x41ggregationServerService\x12+\n\rsum_encrypted\x12\x0c.aggr_params\x1a\x0c.aggr_paramsb\x06proto3')



_AGGR_PARAMS = DESCRIPTOR.message_types_by_name['aggr_params']
aggr_params = _reflection.GeneratedProtocolMessageType('aggr_params', (_message.Message,), {
  'DESCRIPTOR' : _AGGR_PARAMS,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:aggr_params)
  })
_sym_db.RegisterMessage(aggr_params)

_AGGREGATIONSERVERSERVICE = DESCRIPTOR.services_by_name['AggregationServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AGGR_PARAMS._serialized_start=34
  _AGGR_PARAMS._serialized_end=88
  _AGGREGATIONSERVERSERVICE._serialized_start=90
  _AGGREGATIONSERVERSERVICE._serialized_end=161
# @@protoc_insertion_point(module_scope)
