# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_aggregate_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tenseal_aggregate_server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1etenseal_aggregate_server.proto\"K\n\x0clocal_params\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x12\n\nsample_num\x18\x02 \x01(\x05\x12\x12\n\nparams_msg\x18\x03 \x01(\x0c\"6\n\x0b\x61ggr_params\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x12\n\nparams_msg\x18\x02 \x01(\x0c\"9\n\x0eupdate_request\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x12\n\nsample_num\x18\x02 \x01(\x05\"3\n\x0fupdate_response\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x12\x12\n\nparams_msg\x18\x02 \x01(\x0c\"E\n\x14intersection_request\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x13\n\x0brequest_msg\x18\x03 \x03(\x05\"G\n\x15intersection_response\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x14\n\x0cresponse_msg\x18\x03 \x03(\x05\"1\n\x15identification_verify\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\"k\n\x1bintersection_sequence_index\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x16\n\x0esequence_index\x18\x03 \x01(\x05\x12\x1a\n\x12total_participator\x18\x04 \x01(\x05\"R\n\x1a\x64\x61ta_server_status_request\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x1a\n\x12\x64\x61ta_server_status\x18\x03 \x03(\t\"Q\n\x1a\x61gg_server_status_response\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x19\n\x11\x61gg_server_status\x18\x03 \x03(\t2\xed\x02\n\x16\x41ggregateServerService\x12,\n\rsum_encrypted\x12\r.local_params\x1a\x0c.aggr_params\x12\x36\n\x11\x62oolean_is_update\x12\x0f.update_request\x1a\x10.update_response\x12\x41\n\x10get_intersection\x12\x15.intersection_request\x1a\x16.intersection_response\x12W\n\x1fget_intersection_sequence_index\x12\x16.identification_verify\x1a\x1c.intersection_sequence_index\x12Q\n\x15get_agg_server_status\x12\x1b.data_server_status_request\x1a\x1b.agg_server_status_responseb\x06proto3'
)




_LOCAL_PARAMS = _descriptor.Descriptor(
  name='local_params',
  full_name='local_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_rank', full_name='local_params.client_rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_num', full_name='local_params.sample_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params_msg', full_name='local_params.params_msg', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=109,
)


_AGGR_PARAMS = _descriptor.Descriptor(
  name='aggr_params',
  full_name='aggr_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_rank', full_name='aggr_params.client_rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params_msg', full_name='aggr_params.params_msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=165,
)


_UPDATE_REQUEST = _descriptor.Descriptor(
  name='update_request',
  full_name='update_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_rank', full_name='update_request.client_rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_num', full_name='update_request.sample_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=224,
)


_UPDATE_RESPONSE = _descriptor.Descriptor(
  name='update_response',
  full_name='update_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='update_response.flag', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params_msg', full_name='update_response.params_msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=277,
)


_INTERSECTION_REQUEST = _descriptor.Descriptor(
  name='intersection_request',
  full_name='intersection_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='intersection_request.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='intersection_request.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_msg', full_name='intersection_request.request_msg', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=348,
)


_INTERSECTION_RESPONSE = _descriptor.Descriptor(
  name='intersection_response',
  full_name='intersection_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='intersection_response.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='intersection_response.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_msg', full_name='intersection_response.response_msg', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=421,
)


_IDENTIFICATION_VERIFY = _descriptor.Descriptor(
  name='identification_verify',
  full_name='identification_verify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='identification_verify.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='identification_verify.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=472,
)


_INTERSECTION_SEQUENCE_INDEX = _descriptor.Descriptor(
  name='intersection_sequence_index',
  full_name='intersection_sequence_index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='intersection_sequence_index.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='intersection_sequence_index.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_index', full_name='intersection_sequence_index.sequence_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_participator', full_name='intersection_sequence_index.total_participator', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=581,
)


_DATA_SERVER_STATUS_REQUEST = _descriptor.Descriptor(
  name='data_server_status_request',
  full_name='data_server_status_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='data_server_status_request.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='data_server_status_request.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_server_status', full_name='data_server_status_request.data_server_status', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=665,
)


_AGG_SERVER_STATUS_RESPONSE = _descriptor.Descriptor(
  name='agg_server_status_response',
  full_name='agg_server_status_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='agg_server_status_response.cid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qid', full_name='agg_server_status_response.qid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='agg_server_status', full_name='agg_server_status_response.agg_server_status', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=748,
)

DESCRIPTOR.message_types_by_name['local_params'] = _LOCAL_PARAMS
DESCRIPTOR.message_types_by_name['aggr_params'] = _AGGR_PARAMS
DESCRIPTOR.message_types_by_name['update_request'] = _UPDATE_REQUEST
DESCRIPTOR.message_types_by_name['update_response'] = _UPDATE_RESPONSE
DESCRIPTOR.message_types_by_name['intersection_request'] = _INTERSECTION_REQUEST
DESCRIPTOR.message_types_by_name['intersection_response'] = _INTERSECTION_RESPONSE
DESCRIPTOR.message_types_by_name['identification_verify'] = _IDENTIFICATION_VERIFY
DESCRIPTOR.message_types_by_name['intersection_sequence_index'] = _INTERSECTION_SEQUENCE_INDEX
DESCRIPTOR.message_types_by_name['data_server_status_request'] = _DATA_SERVER_STATUS_REQUEST
DESCRIPTOR.message_types_by_name['agg_server_status_response'] = _AGG_SERVER_STATUS_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

local_params = _reflection.GeneratedProtocolMessageType('local_params', (_message.Message,), {
  'DESCRIPTOR' : _LOCAL_PARAMS,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:local_params)
  })
_sym_db.RegisterMessage(local_params)

aggr_params = _reflection.GeneratedProtocolMessageType('aggr_params', (_message.Message,), {
  'DESCRIPTOR' : _AGGR_PARAMS,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:aggr_params)
  })
_sym_db.RegisterMessage(aggr_params)

update_request = _reflection.GeneratedProtocolMessageType('update_request', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE_REQUEST,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:update_request)
  })
_sym_db.RegisterMessage(update_request)

update_response = _reflection.GeneratedProtocolMessageType('update_response', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE_RESPONSE,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:update_response)
  })
_sym_db.RegisterMessage(update_response)

intersection_request = _reflection.GeneratedProtocolMessageType('intersection_request', (_message.Message,), {
  'DESCRIPTOR' : _INTERSECTION_REQUEST,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:intersection_request)
  })
_sym_db.RegisterMessage(intersection_request)

intersection_response = _reflection.GeneratedProtocolMessageType('intersection_response', (_message.Message,), {
  'DESCRIPTOR' : _INTERSECTION_RESPONSE,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:intersection_response)
  })
_sym_db.RegisterMessage(intersection_response)

identification_verify = _reflection.GeneratedProtocolMessageType('identification_verify', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFICATION_VERIFY,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:identification_verify)
  })
_sym_db.RegisterMessage(identification_verify)

intersection_sequence_index = _reflection.GeneratedProtocolMessageType('intersection_sequence_index', (_message.Message,), {
  'DESCRIPTOR' : _INTERSECTION_SEQUENCE_INDEX,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:intersection_sequence_index)
  })
_sym_db.RegisterMessage(intersection_sequence_index)

data_server_status_request = _reflection.GeneratedProtocolMessageType('data_server_status_request', (_message.Message,), {
  'DESCRIPTOR' : _DATA_SERVER_STATUS_REQUEST,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:data_server_status_request)
  })
_sym_db.RegisterMessage(data_server_status_request)

agg_server_status_response = _reflection.GeneratedProtocolMessageType('agg_server_status_response', (_message.Message,), {
  'DESCRIPTOR' : _AGG_SERVER_STATUS_RESPONSE,
  '__module__' : 'tenseal_aggregate_server_pb2'
  # @@protoc_insertion_point(class_scope:agg_server_status_response)
  })
_sym_db.RegisterMessage(agg_server_status_response)



_AGGREGATESERVERSERVICE = _descriptor.ServiceDescriptor(
  name='AggregateServerService',
  full_name='AggregateServerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=751,
  serialized_end=1116,
  methods=[
  _descriptor.MethodDescriptor(
    name='sum_encrypted',
    full_name='AggregateServerService.sum_encrypted',
    index=0,
    containing_service=None,
    input_type=_LOCAL_PARAMS,
    output_type=_AGGR_PARAMS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='boolean_is_update',
    full_name='AggregateServerService.boolean_is_update',
    index=1,
    containing_service=None,
    input_type=_UPDATE_REQUEST,
    output_type=_UPDATE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_intersection',
    full_name='AggregateServerService.get_intersection',
    index=2,
    containing_service=None,
    input_type=_INTERSECTION_REQUEST,
    output_type=_INTERSECTION_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_intersection_sequence_index',
    full_name='AggregateServerService.get_intersection_sequence_index',
    index=3,
    containing_service=None,
    input_type=_IDENTIFICATION_VERIFY,
    output_type=_INTERSECTION_SEQUENCE_INDEX,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_agg_server_status',
    full_name='AggregateServerService.get_agg_server_status',
    index=4,
    containing_service=None,
    input_type=_DATA_SERVER_STATUS_REQUEST,
    output_type=_AGG_SERVER_STATUS_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGGREGATESERVERSERVICE)

DESCRIPTOR.services_by_name['AggregateServerService'] = _AGGREGATESERVERSERVICE

# @@protoc_insertion_point(module_scope)
