# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transmission.tenseal.tenseal_aggregate_server_pb2 as tenseal__aggregate__server__pb2


class AggregateServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sum_encrypted = channel.unary_unary(
                '/AggregateServerService/sum_encrypted',
                request_serializer=tenseal__aggregate__server__pb2.local_params.SerializeToString,
                response_deserializer=tenseal__aggregate__server__pb2.aggr_params.FromString,
                )
        self.boolean_is_update = channel.unary_unary(
                '/AggregateServerService/boolean_is_update',
                request_serializer=tenseal__aggregate__server__pb2.update_request.SerializeToString,
                response_deserializer=tenseal__aggregate__server__pb2.update_response.FromString,
                )
        self.get_intersection = channel.unary_unary(
                '/AggregateServerService/get_intersection',
                request_serializer=tenseal__aggregate__server__pb2.intersection_request.SerializeToString,
                response_deserializer=tenseal__aggregate__server__pb2.intersection_response.FromString,
                )


class AggregateServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sum_encrypted(self, request, context):
        """AggregateServer provides the interface, client remotes the call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def boolean_is_update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_intersection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregateServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sum_encrypted': grpc.unary_unary_rpc_method_handler(
                    servicer.sum_encrypted,
                    request_deserializer=tenseal__aggregate__server__pb2.local_params.FromString,
                    response_serializer=tenseal__aggregate__server__pb2.aggr_params.SerializeToString,
            ),
            'boolean_is_update': grpc.unary_unary_rpc_method_handler(
                    servicer.boolean_is_update,
                    request_deserializer=tenseal__aggregate__server__pb2.update_request.FromString,
                    response_serializer=tenseal__aggregate__server__pb2.update_response.SerializeToString,
            ),
            'get_intersection': grpc.unary_unary_rpc_method_handler(
                    servicer.get_intersection,
                    request_deserializer=tenseal__aggregate__server__pb2.intersection_request.FromString,
                    response_serializer=tenseal__aggregate__server__pb2.intersection_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AggregateServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AggregateServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sum_encrypted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AggregateServerService/sum_encrypted',
            tenseal__aggregate__server__pb2.local_params.SerializeToString,
            tenseal__aggregate__server__pb2.aggr_params.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def boolean_is_update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AggregateServerService/boolean_is_update',
            tenseal__aggregate__server__pb2.update_request.SerializeToString,
            tenseal__aggregate__server__pb2.update_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_intersection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AggregateServerService/get_intersection',
            tenseal__aggregate__server__pb2.intersection_request.SerializeToString,
            tenseal__aggregate__server__pb2.intersection_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
