# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_parse_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atenseal_parse_server.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8c\x01\n\x16query_msg_client_proxy\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x62_name\x18\x03 \x01(\t\x12\x12\n\ntable_name\x18\x04 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x05 \x01(\t\x12\n\n\x02op\x18\x06 \x01(\t\x12\x12\n\nip_address\x18\x07 \x01(\t2V\n\x12ParseServerService\x12@\n\rparse_request\x12\x17.query_msg_client_proxy\x1a\x16.google.protobuf.Emptyb\x06proto3')



_QUERY_MSG_CLIENT_PROXY = DESCRIPTOR.message_types_by_name['query_msg_client_proxy']
query_msg_client_proxy = _reflection.GeneratedProtocolMessageType('query_msg_client_proxy', (_message.Message,), {
  'DESCRIPTOR' : _QUERY_MSG_CLIENT_PROXY,
  '__module__' : 'tenseal_parse_server_pb2'
  # @@protoc_insertion_point(class_scope:query_msg_client_proxy)
  })
_sym_db.RegisterMessage(query_msg_client_proxy)

_PARSESERVERSERVICE = DESCRIPTOR.services_by_name['ParseServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERY_MSG_CLIENT_PROXY._serialized_start=60
  _QUERY_MSG_CLIENT_PROXY._serialized_end=200
  _PARSESERVERSERVICE._serialized_start=202
  _PARSESERVERSERVICE._serialized_end=288
# @@protoc_insertion_point(module_scope)
