# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transmission.tenseal.tenseal_data_pb2 as tenseal__data__pb2


class DatabaseServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryOperation = channel.unary_unary(
                '/DatabaseServerService/QueryOperation',
                request_serializer=tenseal__data__pb2.requestOP.SerializeToString,
                response_deserializer=tenseal__data__pb2.responseEncResult.FromString,
                )
        self.NoiseQueryOperation = channel.unary_unary(
                '/DatabaseServerService/NoiseQueryOperation',
                request_serializer=tenseal__data__pb2.requestOP.SerializeToString,
                response_deserializer=tenseal__data__pb2.responseEncResult.FromString,
                )


class DatabaseServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NoiseQueryOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOperation,
                    request_deserializer=tenseal__data__pb2.requestOP.FromString,
                    response_serializer=tenseal__data__pb2.responseEncResult.SerializeToString,
            ),
            'NoiseQueryOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.NoiseQueryOperation,
                    request_deserializer=tenseal__data__pb2.requestOP.FromString,
                    response_serializer=tenseal__data__pb2.responseEncResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatabaseServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatabaseServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseServerService/QueryOperation',
            tenseal__data__pb2.requestOP.SerializeToString,
            tenseal__data__pb2.responseEncResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NoiseQueryOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatabaseServerService/NoiseQueryOperation',
            tenseal__data__pb2.requestOP.SerializeToString,
            tenseal__data__pb2.responseEncResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
