# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import transmission.tenseal.tenseal_parse_server_pb2 as tenseal__parse__server__pb2


class ParseServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.parse_request = channel.unary_unary(
                '/ParseServerService/parse_request',
                request_serializer=tenseal__parse__server__pb2.query_msg_client_proxy.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ParseServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def parse_request(self, request, context):
        """requestServer provides the interface, clientProxy remotes the call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParseServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'parse_request': grpc.unary_unary_rpc_method_handler(
                    servicer.parse_request,
                    request_deserializer=tenseal__parse__server__pb2.query_msg_client_proxy.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ParseServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParseServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def parse_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ParseServerService/parse_request',
            tenseal__parse__server__pb2.query_msg_client_proxy.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
