# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_parseServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19request_parseServer.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x81\x01\n\x0crequestQuery\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x62_name\x18\x03 \x01(\t\x12\x12\n\ntable_name\x18\x04 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x05 \x01(\t\x12\n\n\x02op\x18\x06 \x01(\t\x12\x11\n\tipaddress\x18\x07 \x01(\t2M\n\x12ParseServerService\x12\x37\n\x0eRequestParsing\x12\r.requestQuery\x1a\x16.google.protobuf.Emptyb\x06proto3')



_REQUESTQUERY = DESCRIPTOR.message_types_by_name['requestQuery']
requestQuery = _reflection.GeneratedProtocolMessageType('requestQuery', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTQUERY,
  '__module__' : 'request_parseServer_pb2'
  # @@protoc_insertion_point(class_scope:requestQuery)
  })
_sym_db.RegisterMessage(requestQuery)

_PARSESERVERSERVICE = DESCRIPTOR.services_by_name['ParseServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTQUERY._serialized_start=59
  _REQUESTQUERY._serialized_end=188
  _PARSESERVERSERVICE._serialized_start=190
  _PARSESERVERSERVICE._serialized_end=267
# @@protoc_insertion_point(module_scope)
