# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import request_data_pb2 as request__data__pb2


class RequestTransmissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestParsing = channel.unary_unary(
                '/RequestTransmission/RequestParsing',
                request_serializer=request__data__pb2.requestOP.SerializeToString,
                response_deserializer=request__data__pb2.requestOP.FromString,
                )


class RequestTransmissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestParsing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequestTransmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestParsing': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestParsing,
                    request_deserializer=request__data__pb2.requestOP.FromString,
                    response_serializer=request__data__pb2.requestOP.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RequestTransmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RequestTransmission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestParsing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RequestTransmission/RequestParsing',
            request__data__pb2.requestOP.SerializeToString,
            request__data__pb2.requestOP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
