# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12request_data.proto\"7\n\x0crequestQuery\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x62_name\x18\x02 \x01(\t\x12\n\n\x02op\x18\x03 \x01(\t\"\x16\n\x07results\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\x32\x66\n\x13RequestTransmission\x12)\n\x0eRequestParsing\x12\r.requestQuery\x1a\x08.results\x12$\n\x0eRequestDecrypt\x12\x08.results\x1a\x08.resultsb\x06proto3')



_REQUESTQUERY = DESCRIPTOR.message_types_by_name['requestQuery']
_RESULTS = DESCRIPTOR.message_types_by_name['results']
requestQuery = _reflection.GeneratedProtocolMessageType('requestQuery', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTQUERY,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:requestQuery)
  })
_sym_db.RegisterMessage(requestQuery)

results = _reflection.GeneratedProtocolMessageType('results', (_message.Message,), {
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:results)
  })
_sym_db.RegisterMessage(results)

_REQUESTTRANSMISSION = DESCRIPTOR.services_by_name['RequestTransmission']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTQUERY._serialized_start=22
  _REQUESTQUERY._serialized_end=77
  _RESULTS._serialized_start=79
  _RESULTS._serialized_end=101
  _REQUESTTRANSMISSION._serialized_start=103
  _REQUESTTRANSMISSION._serialized_end=205
# @@protoc_insertion_point(module_scope)
