# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12request_data.proto\x1a\x1bgoogle/protobuf/empty.proto\"Z\n\x0crequestProxy\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x62_name\x18\x03 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x04 \x01(\t\x12\n\n\x02op\x18\x05 \x01(\t\"m\n\x0crequestQuery\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x0f\n\x07\x64\x62_name\x18\x03 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x04 \x01(\t\x12\n\n\x02op\x18\x05 \x01(\t\x12\x11\n\tipaddress\x18\x06 \x01(\t\"R\n\x10requestEncResult\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x11\n\tipaddress\x18\x03 \x01(\t\x12\x11\n\tencResult\x18\x04 \x01(\x0c\"?\n\x10requestDecResult\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\x0b\n\x03qid\x18\x02 \x01(\x05\x12\x11\n\tresult\x18\x03 \x01(\x0c\" \n\x0eresponseResult\x12\x0e\n\x06result\x18\x01 \x01(\x0c\"\x14\n\x04\x66lag\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x32\xf7\x01\n\x13RequestTransmission\x12.\n\x0cRequestProxy\x12\r.client_query_msg\x1a\x0f.query_result\x12\x37\n\x0eRequestParsing\x12\r.requestQuery\x1a\x16.google.protobuf.Empty\x12;\n\x0eRequestDecrypt\x12\x11.requestEncResult\x1a\x16.google.protobuf.Empty\x12:\n\rRequestResult\x12\x11.query_result\x1a\x16.google.protobuf.Emptyb\x06proto3')



_REQUESTPROXY = DESCRIPTOR.message_types_by_name['client_query_msg']
_REQUESTQUERY = DESCRIPTOR.message_types_by_name['requestQuery']
_REQUESTENCRESULT = DESCRIPTOR.message_types_by_name['requestEncResult']
_REQUESTDECRESULT = DESCRIPTOR.message_types_by_name['query_result']
_RESPONSERESULT = DESCRIPTOR.message_types_by_name['query_result']
_FLAG = DESCRIPTOR.message_types_by_name['flag']
requestProxy = _reflection.GeneratedProtocolMessageType('client_query_msg', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTPROXY,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:client_query_msg)
  })
_sym_db.RegisterMessage(requestProxy)

requestQuery = _reflection.GeneratedProtocolMessageType('requestQuery', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTQUERY,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:requestQuery)
  })
_sym_db.RegisterMessage(requestQuery)

requestEncResult = _reflection.GeneratedProtocolMessageType('requestEncResult', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTENCRESULT,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:requestEncResult)
  })
_sym_db.RegisterMessage(requestEncResult)

requestDecResult = _reflection.GeneratedProtocolMessageType('query_result', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDECRESULT,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:query_result)
  })
_sym_db.RegisterMessage(requestDecResult)

responseResult = _reflection.GeneratedProtocolMessageType('query_result', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSERESULT,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:query_result)
  })
_sym_db.RegisterMessage(responseResult)

flag = _reflection.GeneratedProtocolMessageType('flag', (_message.Message,), {
  'DESCRIPTOR' : _FLAG,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:flag)
  })
_sym_db.RegisterMessage(flag)

_REQUESTTRANSMISSION = DESCRIPTOR.services_by_name['RequestTransmission']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTPROXY._serialized_start=51
  _REQUESTPROXY._serialized_end=141
  _REQUESTQUERY._serialized_start=143
  _REQUESTQUERY._serialized_end=252
  _REQUESTENCRESULT._serialized_start=254
  _REQUESTENCRESULT._serialized_end=336
  _REQUESTDECRESULT._serialized_start=338
  _REQUESTDECRESULT._serialized_end=401
  _RESPONSERESULT._serialized_start=403
  _RESPONSERESULT._serialized_end=435
  _FLAG._serialized_start=437
  _FLAG._serialized_end=457
  _REQUESTTRANSMISSION._serialized_start=460
  _REQUESTTRANSMISSION._serialized_end=707
# @@protoc_insertion_point(module_scope)
