# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12request_data.proto\"$\n\trequestOP\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x32?\n\x13RequestTransmission\x12(\n\x0eRequestParsing\x12\n.requestOP\x1a\n.requestOPb\x06proto3')



_REQUESTOP = DESCRIPTOR.message_types_by_name['requestOP']
requestOP = _reflection.GeneratedProtocolMessageType('requestOP', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTOP,
  '__module__' : 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:requestOP)
  })
_sym_db.RegisterMessage(requestOP)

_REQUESTTRANSMISSION = DESCRIPTOR.services_by_name['RequestTransmission']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTOP._serialized_start=22
  _REQUESTOP._serialized_end=58
  _REQUESTTRANSMISSION._serialized_start=60
  _REQUESTTRANSMISSION._serialized_end=123
# @@protoc_insertion_point(module_scope)
